// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpawvpfqesabrkujjvkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwYXd2cGZxZXNhYnJrdWpqdmtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTE0MzcsImV4cCI6MjA2ODQyNzQzN30.wSo7TNsEj9ggLQoG8_rQ_t5OcVe7aRWFmpvJ-wOX4-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});